python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuAntiTauIsoJanX && mt<30 && l1_decayMode==1 && Xcat_J0X' -a -b -N 'ZeroJet_AntiMuAntiTauIsoLowMTDecayMode1'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiTauIsoJanX && mt<30 && l1_decayMode==1 && Xcat_J0X' -a -b -N 'ZeroJet_AntiTauIsoLowMTDecayMode1'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuIsoJanX && mt<30 && l1_decayMode==1 && Xcat_J0X' -a -b -N 'ZeroJet_AntiMuIsoLowMTDecayMode1'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuAntiTauIsoJanX && mt>60 && l1_decayMode==1 && Xcat_J0X' -a -b -N 'ZeroJet_AntiMuAntiTauIsoHighMTDecayMode1'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiTauIsoJanX && mt>60 && l1_decayMode==1 && Xcat_J0X' -a -b -N 'ZeroJet_AntiTauIsoHighMTDecayMode1'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuIsoJanX && mt>60 && l1_decayMode==1 && Xcat_J0X' -a -b -N 'ZeroJet_AntiMuIsoHighMTDecayMode1'

python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuAntiTauIsoJanX && mt<30 && l1_decayMode==1 && Xcat_J1X' -a -b -N 'OneJet_AntiMuAntiTauIsoLowMTDecayMode1'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiTauIsoJanX && mt<30 && l1_decayMode==1 && Xcat_J1X' -a -b -N 'OneJet_AntiTauIsoLowMTDecayMode1'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuIsoJanX && mt<30 && l1_decayMode==1 && Xcat_J1X' -a -b -N 'OneJet_AntiMuIsoLowMTDecayMode1'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuAntiTauIsoJanX && mt>60 && l1_decayMode==1 && Xcat_J1X' -a -b -N 'OneJet_AntiMuAntiTauIsoHighMTDecayMode1'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiTauIsoJanX && mt>60 && l1_decayMode==1 && Xcat_J1X' -a -b -N 'OneJet_AntiTauIsoHighMTDecayMode1'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuIsoJanX && mt>60 && l1_decayMode==1 && Xcat_J1X' -a -b -N 'OneJet_AntiMuIsoHighMTDecayMode1'
