python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuAntiTauIsoJanX && mt<30 && l1_decayMode==0 && Xcat_J0X' -a -b -N 'ZeroJet_AntiMuAntiTauIsoLowMTDecayMode0'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiTauIsoJanX && mt<30 && l1_decayMode==0 && Xcat_J0X' -a -b -N 'ZeroJet_AntiTauIsoLowMTDecayMode0'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuIsoJanX && mt<30 && l1_decayMode==0 && Xcat_J0X' -a -b -N 'ZeroJet_AntiMuIsoLowMTDecayMode0'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuAntiTauIsoJanX && mt>60 && l1_decayMode==0 && Xcat_J0X' -a -b -N 'ZeroJet_AntiMuAntiTauIsoHighMTDecayMode0'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiTauIsoJanX && mt>60 && l1_decayMode==0 && Xcat_J0X' -a -b -N 'ZeroJet_AntiTauIsoHighMTDecayMode0'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuIsoJanX && mt>60 && l1_decayMode==0 && Xcat_J0X' -a -b -N 'ZeroJet_AntiMuIsoHighMTDecayMode0'

python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuAntiTauIsoJanX && mt<30 && l1_decayMode==0 && Xcat_J1X' -a -b -N 'OneJet_AntiMuAntiTauIsoLowMTDecayMode0'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiTauIsoJanX && mt<30 && l1_decayMode==0 && Xcat_J1X' -a -b -N 'OneJet_AntiTauIsoLowMTDecayMode0'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuIsoJanX && mt<30 && l1_decayMode==0 && Xcat_J1X' -a -b -N 'OneJet_AntiMuIsoLowMTDecayMode0'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuAntiTauIsoJanX && mt>60 && l1_decayMode==0 && Xcat_J1X' -a -b -N 'OneJet_AntiMuAntiTauIsoHighMTDecayMode0'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiTauIsoJanX && mt>60 && l1_decayMode==0 && Xcat_J1X' -a -b -N 'OneJet_AntiTauIsoHighMTDecayMode0'
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Jul04TauMu/ tauMu_2012_cfg.py -H nJets -C 'Xcat_Inc_AntiMuIsoJanX && mt>60 && l1_decayMode==0 && Xcat_J1X' -a -b -N 'OneJet_AntiMuIsoHighMTDecayMode0'
