python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Sep19MuTau/ tauMu_2012_cfg.py -C 'Xcat_IncX && mt<30 && Xcat_J0_lowX' -H svfitMass -b  -E
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Sep19MuTau/ tauMu_2012_cfg.py -C 'Xcat_IncX && mt<30 && Xcat_J0_mediumX' -H svfitMass -b  -E
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Sep19MuTau/ tauMu_2012_cfg.py -C 'Xcat_IncX && mt<30 && Xcat_J0_highX' -H svfitMass -b  -E
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Sep19MuTau/ tauMu_2012_cfg.py -C 'Xcat_IncX && mt<30 && Xcat_J1_mediumX' -H svfitMass -b -E
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Sep19MuTau/ tauMu_2012_cfg.py -C 'Xcat_IncX && mt<30 && Xcat_J1_high_mediumhiggsX' -H svfitMass -b -E
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Sep19MuTau/ tauMu_2012_cfg.py -C 'Xcat_IncX && mt<30 && Xcat_J1_high_lowhiggsX' -H svfitMass -b -E
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Sep19MuTau/ tauMu_2012_cfg.py -C 'Xcat_IncX && mt<30 && Xcat_VBF_looseX' -H svfitMass -b -E
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Sep19MuTau/ tauMu_2012_cfg.py -C 'Xcat_IncX && mt<30 && Xcat_VBF_tightX' -H svfitMass -b -E
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Sep19MuTau/ tauMu_2012_cfg.py -C 'Xcat_IncX && mt<30 && Xcat_J1BX' -H svfitMass -b -E
python plot_H2TauTauDataMC_TauMu_All.py /data/steggema/Sep19MuTau/ tauMu_2012_cfg.py -C 'Xcat_IncX && mt<30 && Xcat_0BX' -H svfitMass -b -E
